### ISSUE TITLE
[4.0-dev Atum] Suggestion for Articles View Toolbar (Lots of Button)

### ISSUE THREAD

**Issue by frogydiak** [joomla/40-backend-template#451] opened 2018-07-09 01:38 UTC
Currently when going to Articles view, the toolbar will wrap down and would look like this:

<img width="1474" alt="4 0-dev_default_toolbar" src="https://user-images.githubusercontent.com/1373815/42426556-a2f1d3b6-82dd-11e8-9b8c-badcc560bb20.png">

Since the new Toolbar class can now have a dropdown, maybe it would be a good idea to group all action buttons like:

<img width="970" alt="4 0-dev_long_toolbar" src="https://user-images.githubusercontent.com/1373815/42426588-e2953fee-82dd-11e8-9622-5e24a7b423cb.png">

To create a short toolbar where it does not wrap. This applies to other component views that has a lot of buttons in the toolbar.

**Comment by brianteeman** [comment] 2018-07-09 06:25
Please see https://github.com/joomla/40-backend-template/issues/418

**Comment by ggppdk** [comment] 2018-07-12 21:10
#418 is about similar improvement for edit layout
this issue is about backend managers

i think you mean to link to #348 ?
this is duplicate of #348

**Comment by dgrammatiko** [comment] 2018-07-13 10:17
There is some ongoing work to group buttons (as dropdowns)...

**Comment by wilsonge** [comment] 2018-07-19 19:44
Grouping action buttons is already captured under https://github.com/joomla/40-backend-template/issues/436 which has an action dropdown :) so closing this as a duplicate

**Closed as completed by wilsonge** 2018-07-19 19:44 UTC
